# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Advventure Land Panamá
email: info@adventureland.com
phone: +507 3874166
phone_url: 5073874166
open: L-J 3:00pm - 7:30pm
fb: https://www.facebook.com/adventurelandpty
tw: http://twitter.com
gp: https://plus.google.com/
ig: https://www.instagram.com/adventurelandpty
pi: https://es.pinterest.com/
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
host: "192.168.1.10"
port: 8000
livereload: true     # You no longer need to include --livereload
# Asset configuration
assets:
  cache: .asset-cache
  prefix: "/assets"
  assets:
    - "*"
#  digest: true
  sources:
    - _assets
    - _assets/js
    - _assets/css
    - _assets/fonts
    - _assets/img
    - _assets/images
# Build settings
markdown: kramdown
gems:
  - jekyll-assets
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - .asset-cache/
#livereload: true     # You no longer need to include --livereload
#reload_port: 5678 # If you don't want to use the default port

#Adventure Land - Arrays
attractions: [
{
  "name": "Play<br>Ground",
  "image": "atracciones_playground.jpg",
  "age": "0a",
  "description": "Desde los 6 meses en adelante pueden los niños disfrutar.",
  "link": "atracciones/arena_laser.html"
},
{
  "name": "Arena<br>Laser",
  "image": "atracciones_laser.jpg",
  "age": "10a",
  "description": "Declara la guerra láser en nuestra arena de juegos láser.",
  "link": "atracciones/arena_laser.html"
},
{
  "name": "Course<br>Rope",
  "image": "atracciones_playground.jpg",
  "age": "3a 10a",
  "description": "Pasea por las alturas y desafía tus miedos.",
  "link": "atracciones/arena_laser.html"
},
{
  "name": "Pared de<br>Escalar",
  "image": "atracciones_playground.jpg",
  "age": "3a 10a",
  "description": "Para que los niños intenten llegar a lo más alto.",
  "link": "atracciones/arena_laser.html"
},
{
  "name": "Futbol<br>Town",
  "image": "atracciones_futbol.jpg",
  "age": "10a adultos",
  "description": "Juega tus partidos de fútbol en las mejores canchas de Panamá.",
  "link": "atracciones/arena_laser.html"
},
{
  "name": "igolf<br>",
  "image": "atracciones_igolf.jpg",
  "age": "adultos",
  "description": "Prueba nuestro simulador de golf virtual.",
  "link": "atracciones/arena_laser.html"
}
]
